version: '3'

services:
  jdk8-nanoserver:
    build:
      context: ./8/windows/nanoserver-1809/
      args:
        - VERSION=$REMOTING_VERSION
  jdk8-windowsservercore:
    build:
      context: ./8/windows/windowsservercore-ltsc2019/
      args:
        - VERSION=$REMOTING_VERSION
